from flask import Flask
import mapping
from importlib import reload 	

app = Flask(__name__)

@app.route('/')
def hello():
    reload(mapping)
    help('modules')
    k = __import__('kakuro')
    kakuro_board = [
            [
                -1,
                -1,
                -1,
                -1,
                4,
                0,
                10,
                0,
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
            ],
            [
                -1,
                -1,
                0,
                4,
                0,
                0,
                0,
                0,
                -1,
                -1,
                3,
                0,
                4,
                0,
            ],
            [
                -1,
                -1,
                0,
                3,
                0,
                0,
                0,
                0,
                11,
                4,
                0,
                0,
                0,
                0,
            ],
            [
                -1,
                -1,
                3,
                0,
                4,
                10,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
            ],
            [
                0,
                11,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                4,
                0,
                -1,
                -1,
            ],
            [
                0,
                4,
                0,
                0,
                0,
                0,
                0,
                4,
                0,
                0,
                0,
                0,
                -1,
                -1,
            ],
            [
                -1,
                -1,
                -1,
                -1,
                -1,
                -1,
                0,
                3,
                0,
                0,
                0,
                0,
                -1,
                -1,
            ],
        ]
    result = k.solve_kakuro(kakuro_board)
    return {'result':result}

if __name__ == "__main__":
    app.run()
